<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "crontab".
 *
 * @property int $entity_id 自增ID
 * @property string $name 任务名称
 * @property string $route 任务路由
 * @property string $cron_format 定时任务时间格式
 * @property string $created_at 建立时间
 * @property string $updated_at 更新时间
 * @property int $sticky 是否粘滞到某一个任务执行器，某些任务可以防重
 * @property int $status 1：启用，2：禁用
 * @property string $from_time 开始时间
 * @property string $to_time 结束时间
 * @property string $notes 备注
 * @property string $params 参数，json格式
 */
class Crontab extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'crontab';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'route', 'cron_format'], 'required'],
            [['created_at', 'updated_at', 'from_time', 'to_time'], 'safe'],
            [['sticky', 'status'], 'integer'],
            [['params'], 'string'],
            [['name', 'route', 'cron_format'], 'string', 'max' => 255],
            [['notes'], 'string', 'max' => 16],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'entity_id' => '自增ID',
            'name' => '任务名称',
            'route' => '任务路由',
            'cron_format' => '定时任务时间格式',
            'created_at' => '建立时间',
            'updated_at' => '更新时间',
            'sticky' => '是否粘滞到某一个任务执行器，某些任务可以防重',
            'status' => '1：启用，2：禁用',
            'from_time' => '开始时间',
            'to_time' => '结束时间',
            'notes' => '备注',
            'params' => '参数，json格式',
        ];
    }

    public function beforeSave($insert)
    {
        //记录创建时间
        if ($this->isNewRecord) {
            $this->created_at = date('Y-m-d H:i:s');
        }
        //记录修改审核时间
        $this->updated_at = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
