<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "specification".
 *
 * @property string $id
 * @property string $product_id 商品id
 * @property string $item_detail 规格属性详情，json格式，如："[{"\u4ea7\u5730":"\u6d77\u5357","\u91cd\u91cf":"5\u65a4","\u989c\u8272":"\u7ea2\u8272"}]"
 * @property string $item_ids 对应specification_item中的id，多个用"|"隔开，如：3|8|12
 * @property string $purchase_price 进价
 * @property string $pick_commission 自提佣金
 * @property string $promote_commission 推广佣金
 * @property string $price 售价
 * @property string $qty 库存
 * @property string $create_at
 * @property int $del 是否删除：1-正常，2-删除
 * @property string $image 规格图片
 */
class Specification extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'specification';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('productDb');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['product_id', 'purchase_price', 'price', 'qty', 'barcode'], 'required'],
            [['product_id', 'purchase_price', 'pick_commission', 'promote_commission', 'price', 'qty', 'del'], 'integer'],
            [['create_at', 'image'], 'safe'],
            [['item_detail'], 'string', 'max' => 256],
            [['item_ids', 'image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => '商品ID',
            'item_detail' => '规格属性',
            'item_ids' => 'Item Ids',
            'purchase_price' => '进货价',
            'pick_commission' => '自提佣金',
            'promote_commission' => '推广佣金',
            'price' => '售价',
            'qty' => '库存',
            'create_at' => 'Create At',
            'barcode' => '规格编码',
            'del' => 'Del',
            'image' => '规格图片',
        ];
    }

    public function beforeSave($insert)
    {
        //记录创建时间
        if ($this->isNewRecord) {
            $this->create_at = date('Y-m-d H:i:s');
        }
        if (!$this->item_ids) {
            $this->item_ids = '';
        }
        $this->item_ids = $this->item_ids ?: '';
        $this->del = $this->del ?: 1;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
