<?php

namespace common\models;

use Yii;
use framework\db\ActiveRecord;

/**
 * This is the model class for table "category".
 *
 * @property string $id
 * @property string $name 分类名称
 * @property int $parent_id
 * @property string $path 路径，记录祖辈分类id，比如：5/122/587
 * @property int $level 层级，目前有1，2，3
 * @property string $img 分类图片，目前只有三级分类有
 * @property string $create_at 创建时间
 * @property string $update_at 更新时间
 * @property int $del 是否删除：1-正常，2-删除
 */
class Category extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('productDb');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'parent_id', 'path', 'level'], 'required'],
            [['parent_id', 'level', 'del'], 'integer'],
            [['create_at', 'update_at'], 'safe'],
            [['name', 'path'], 'string', 'max' => 100],
            [['img'], 'string', 'max' => 256],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', '名称'),
            'parent_id' => Yii::t('app', '父分类ID'),
            'path' => Yii::t('app', '路径'),
            'level' => Yii::t('app', '级别'),
            'img' => Yii::t('app', '图片'),
            'create_at' => Yii::t('app', 'Create At'),
            'update_at' => Yii::t('app', 'Update At'),
            'del' => Yii::t('app', 'Del'),
        ];
    }

    public function beforeSave($insert)
    {
        //记录创建时间
        if ($this->isNewRecord) {
            $this->create_at = date('Y-m-d H:i:s');
        }
        //记录修改审核时间
        $this->update_at = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
