<?php

namespace common\models;

use Yii;
use framework\db\ActiveRecord;

/**
 * This is the model class for table "specification_item".
 *
 * @property int $id
 * @property string $product_id 商品id
 * @property string $specification_name 规格类目名称
 * @property string $specification_value 规格类目值
 * @property string $create_at 创建时间
 * @property int $del 是否删除：1-正常，2-删除
 */
class SpecificationItem extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'specification_item';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('productDb');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['product_id', 'specification_name', 'specification_value'], 'required'],
            [['id', 'product_id', 'del'], 'integer'],
            [['create_at'], 'safe'],
            [['specification_name', 'specification_value'], 'string', 'max' => 100],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => '商品ID',
            'specification_name' => '规格类目',
            'specification_value' => '规格值',
            'create_at' => 'Create At',
            'del' => 'Del',
        ];
    }

    public function beforeSave($insert)
    {
        //记录创建时间
        if ($this->isNewRecord) {
            $this->create_at = date('Y-m-d H:i:s');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
